package com.mentormentee.core.domain;

public enum CollegeName {
    HUMANITIES, BUSINESS, AGRICULTURE, VETERINARYMEDICINE,
    BIOHEALTHSYSTEM, BIOHEALTH, SOCIALSCIENCES, ENGINEERING,
    EDUCATION, PHARMACY, INTERDISCIPLINARYSTUDIES, NATURESCIENCE,
    COMPUTERENGINEERING, HUMANECOLOGY, MEDICINE, CONVERGENCE
}


